/**:
  ros__parameters:
    gait:
      knee_orientation : ">>"
      pantograph_leg : false
      odom_scaler: 0.9
      max_linear_velocity_x : 0.6
      max_linear_velocity_y : 0.6
      max_angular_velocity_z : 1.8
      com_x_translation: 0.0
      swing_height : 0.04
      stance_depth : 0.01
      stance_duration : 0.25
      nominal_height : 0.225
